#define CATCH_CONFIG_MAIN
#include "catch.h"

#include "bfloat16/bfloat16_tests.h"
#include "dimensions/dimensions_tests.h"
#include "dimensions/region_tests.h"
#include "symd_register/symd_register_float_tests.h"
#include "symd_register/symd_register_int_tests.h"
#include "symd_register/symd_register_bfloat16_tests.h"
#include "stencil_borders/stencil_borders_tests.h"
#include "map/conversion_tests.h"
#include "map/exp_tests.h"
#include "map/log_tests.h"
#include "map/broadcast_tests.h"
#include "map/map_tests.h"
#include "reduce/reduction_tests.h"
